[package]
name = "g-k-crates-io-client"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/g-k/g-k-crates-io-client"
description = """
A fork of the crates-io package for interacting with crates.io
"""

[lib]
name = "g_k_crates_io_client"
path = "lib.rs"

[dependencies]
curl = "0.2"
url = "0.2"
rustc-serialize = "0.3"
